# Generated by Django 4.2.23 on 2025-06-25 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("simple", "Pack Simple"),
                            ("premium", "Pack Premium"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField()),
                ("features", models.JSONField(default=list)),
            ],
        ),
        migrations.AddField(
            model_name="notification",
            name="related_subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="core.subscription",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("subscription", "Nouvelle souscription"),
                    ("system", "Notification système"),
                    ("user", "Notification utilisateur"),
                ],
                default="system",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="pack",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.subscriptionpack",
            ),
        ),
    ]
